Tables:
`order`           O ( O.id, O.d, O.name, O.idproduct, O.qty, O.name2 )
order_archive    OA ( OA.id, OA.d, OA.name, OA.idproduct, OA.qty, OA.name2 )
hu                H ( H.hu, H.idorder, H.qty, H.idstep_grp )
plan              N ( N.idproduct_grp, N.idstep_grp, N.qty )
process           R ( R.idstep_grp, R.idstep, R.n )
product           P ( P.id, P.idproduct_sgrp, P.nr, P.name )
product_grp      PG ( PG.id, PG.nr, PG.name )
product_sgrp     PS ( PS.id, PS.idproduct_grp, PS.nr, PS.name )
step              S ( S.id, S.nr, S.name )
step_grp         SG ( SG.id, SG.nr, SG.name )
tt_event          E ( E.dt, E.dtend, E.idplace, E.idstep, E.idworker, E.hu, E.isArchived )
tt_event_archive EA ( EA.dt, EA.dtend, EA.idplace, EA.idstep, EA.idworker, EA.hu )
tt_place          L ( L.id, L.name, L.mapX, L.mapY, L.dtlast, L.tags, L.idstep )
worker            W ( W.id, W.nr, W.name, W.grp )